vim.opt.expandtab       = true
vim.opt.shiftwidth      = 4
vim.opt.tabstop         = 4
vim.opt.expandtab       = false
vim.opt.hidden          = true
vim.opt.termguicolors   = true
vim.opt.wrap            = false
vim.opt.linespace       = 8
vim.opt.cursorline      = true
vim.opt.wildignore      = '.git, *.obj, */node_modules'
